import logging
import re
import xml.etree.ElementTree as ET

from pydantic import BaseModel, Field, ValidationError

TOOL_PATTERN = re.compile(r"<tool\b[^>]*?/\s*>", re.IGNORECASE)
logger = logging.getLogger(__name__)


class ToolCall(BaseModel):
    name: str = Field(min_length=1)
    attributes: dict[str, str] = Field(default_factory=dict)


def parse_tool_calls(
    response: str,
) -> tuple[str, list[ToolCall]]:
    """
    Extract tool calls from an AI response.

    Tool calls must use XML-style self-closing tags:

        <tool name="search" query="hello"/>

    Args:
        response: The raw response generated by the AI.

    Returns:
        A tuple containing:
        - The response with tool calls removed.
        - A list of parsed ToolCall objects.
    """
    tool_calls: list[ToolCall] = []

    def replace_tool(match: re.Match[str]) -> str:
        tool_xml = match.group(0)

        try:
            element = ET.fromstring(tool_xml)

            if element.tag.lower() != "tool":
                return tool_xml

            name = element.attrib.pop("name", None)

            if not name:
                return tool_xml

            tool_call = ToolCall(
                name=name,
                attributes=dict(element.attrib),
            )

            tool_calls.append(tool_call)

            # Remove the tool call from the final response.
            return ""

        except (ET.ParseError, ValidationError) as exc:
            # Keep malformed tool calls in the response rather
            # than breaking the entire AI response pipeline.
            logger.warning(
                "Failed to parse tool call %r: %s",
                tool_xml,
                exc,
            )
            return tool_xml

    cleaned_response = TOOL_PATTERN.sub(
        replace_tool,
        response,
    )

    # Clean up excessive whitespace left behind after removing
    # tool calls.
    cleaned_response = re.sub(
        r"\n{3,}",
        "\n\n",
        cleaned_response,
    ).strip()

    return cleaned_response, tool_calls
