import logging
import re

from pydantic import BaseModel, Field, ValidationError

# Pattern for tool calls like:
# <tool:join_vc>
# <tool:leave_vc>
# <tool:queue, action:add, query:"song name">
# <tool:queue, action:remove, query:"song title">
# <tool:skip>
# <tool:skip, query:"song name">
# <tool:pause>
# <tool:resume>
# <tool:stop>
# <tool:loop>
# <tool:volume, level:50>
TOOL_PATTERN = re.compile(r"<tool:(\w+)(?:\s*,\s*([^>]*?))?>", re.IGNORECASE)
logger = logging.getLogger(__name__)


class ToolCall(BaseModel):
    name: str = Field(min_length=1)
    attributes: dict[str, str] = Field(default_factory=dict)


def _parse_attributes(attr_string: str | None) -> dict[str, str]:
    """
    Parse attribute string from tool call.

    Supports formats like:
    - "action:add, query:\"song name\""
    - "action:add"
    - None or empty string returns empty dict

    Args:
        attr_string: The attribute portion of the tool call.

    Returns:
        A dictionary of attribute name to value mappings.
    """
    if not attr_string:
        return {}

    attributes: dict[str, str] = {}

    # Split by comma, but be careful with quoted values
    parts = []
    current_part = ""
    in_quotes = False

    for char in attr_string:
        if char == '"':
            in_quotes = not in_quotes
            current_part += char
        elif char == "," and not in_quotes:
            parts.append(current_part.strip())
            current_part = ""
        else:
            current_part += char

    if current_part.strip():
        parts.append(current_part.strip())

    for part in parts:
        if ":" in part or "=" in part:
            # Support both : and = as separators
            if ":" in part:
                key, _, value = part.partition(":")
            else:
                key, _, value = part.partition("=")
            key = key.strip()
            value = value.strip()
            # Remove surrounding quotes if present (both single and double)
            if (value.startswith('"') and value.endswith('"')) or \
               (value.startswith("'") and value.endswith("'")):
                value = value[1:-1]
            if key:
                attributes[key] = value

    return attributes


def parse_tool_calls(
    response: str,
) -> tuple[str, list[ToolCall]]:
    """
    Extract tool calls from an AI response.

    Tool calls use the format:

        <tool:tool_name>
        <tool:tool_name, attr1:value1, attr2:"value with spaces">

    Examples:
        <tool:join_vc>
        <tool:leave_vc>
        <tool:queue, action:add, query:"song name">
        <tool:queue, action:remove, query:"song title">
        <tool:skip>
        <tool:skip, query:"song name"> - Skip to a specific song in queue
        <tool:pause> - Pause the current song
        <tool:resume> - Resume paused playback
        <tool:stop> - Stop playback and clear queue
        <tool:loop> - Toggle loop mode (off → track → queue → off)
        <tool:volume, level:50> - Set volume to 50%

    Args:
        response: The raw response generated by the AI.

    Returns:
        A tuple containing:
        - The response with tool calls removed.
        - A list of parsed ToolCall objects.
    """
    tool_calls: list[ToolCall] = []

    def replace_tool(match: re.Match[str]) -> str:
        tool_name = match.group(1)
        attr_string = match.group(2) if len(match.groups()) > 1 else None

        try:
            attributes = _parse_attributes(attr_string)

            tool_call = ToolCall(
                name=tool_name,
                attributes=attributes,
            )

            tool_calls.append(tool_call)

            # Remove the tool call from the final response.
            return ""

        except ValidationError as exc:
            # Keep malformed tool calls in the response rather
            # than breaking the entire AI response pipeline.
            logger.warning(
                "Failed to parse tool call %r: %s",
                match.group(0),
                exc,
            )
            return match.group(0)

    cleaned_response = TOOL_PATTERN.sub(
        replace_tool,
        response,
    )

    # Clean up excessive whitespace left behind after removing
    # tool calls.
    cleaned_response = re.sub(
        r"\n{3,}",
        "\n\n",
        cleaned_response,
    ).strip()

    return cleaned_response, tool_calls
